[project]
name = "deteccao-de-fraude"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Diego Neves - lnx", email = "pdcassiano@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
deteccao-de-fraude = "deteccao_de_fraude:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
